### ISSUE TITLE
Continue checkout button doesn't work as Guest

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#110]
After you fill all the info from Your Personal Details, Continue button doesn't work.

No console logs, no popup error..

**Comment by TheCartpenter** [comment]
Server error logs. More information is needed here on how to reproduce the issue. Please use the template.

**Comment by condor2** [comment]
Warning: Undefined array key "firstname" in catalog\controller\checkout\guest.php on line 164
Unknown: trim(): Passing null to parameter #1 ($string) of type string is deprecated in catalog\controller\checkout\guest.php on line 164
Warning: Undefined array key "lastname" in catalog\controller\checkout\guest.php on line 168
Unknown: trim(): Passing null to parameter #1 ($string) of type string is deprecated in catalog\controller\checkout\guest.php on line 168
Warning: Undefined array key "email" in catalog\controller\checkout\guest.php on line 172
Unknown: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in system\helper\utf8.php on line 6
Warning: Undefined array key "email" in catalog\controller\checkout\guest.php on line 172
Warning: Undefined array key "telephone" in catalog\controller\checkout\guest.php on line 176
Unknown: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in oc3\system\helper\utf8.php on line 6
Warning: Undefined array key "address_1" in catalog\controller\checkout\guest.php on line 180
Unknown: trim(): Passing null to parameter #1 ($string) of type string is deprecated in catalog\controller\checkout\guest.php on line 180
Warning: Undefined array key "city" in catalog\controller\checkout\guest.php on line 184
Unknown: trim(): Passing null to parameter #1 ($string) of type string is deprecated in catalog\controller\checkout\guest.php on line 184
Warning: Undefined array key "country_id" in catalog\controller\checkout\guest.php on line 190

**Comment by TheCartpenter** [comment]
Trim deprecation messages. Working on it now.

**Comment by TheCartpenter** [comment]
Task completed: https://github.com/opencart/opencart-3/commit/91fd676f0974d95ff816e899b6480a2b5c2fefd7 .

**Comment by condor2** [comment]
Same issue

Warning: Undefined array key "firstname" in catalog\controller\checkout\guest.php on line 164
Unknown: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in system\helper\utf8.php on line 6

Warning: Undefined array key "lastname" in catalog\controller\checkout\guest.php on line 168
Unknown: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in system\helper\utf8.php on line 6

Warning: Undefined array key "email" in catalog\controller\checkout\guest.php on line 172
Unknown: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in system\helper\utf8.php on line 6

Warning: Undefined array key "telephone" in catalog\controller\checkout\guest.php on line 176
Unknown: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in system\helper\utf8.php on line 6

Warning: Undefined array key "address_1" in catalog\controller\checkout\guest.php on line 180
Unknown: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in system\helper\utf8.php on line 6

Warning: Undefined array key "city" in catalog\controller\checkout\guest.php on line 184
Unknown: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in system\helper\utf8.php on line 6

Warning: Undefined array key "country_id" in catalog\controller\checkout\guest.php on line 190
TypeError: ModelLocalisationCountry::getCountry(): Argument #1 ($country_id) must be of type int, null given, called in system\storage\modification\system\engine\loader.php on line 243
in catalog\model\localisation\country.php on line 3

**Comment by TheCartpenter** [comment]
Changed conventional helper utf-8 function names as per MB: https://github.com/opencart/opencart-3/commit/dbafac3a9b4adffbda447ee7c39cb26d7e280c6a . See if the issue can be reproduced, since.
