### ISSUE TITLE
Type parameters error in google when you checkout as customer

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#111]
TypeError: ControllerExtensionAdvertiseGoogle::before_checkout_success(): Argument #2 ($data) must be of type array, null given, called in system\storage\modification\system\engine\action.php on line 75 in catalog\controller\extension\advertise\google.php on line 41

**Comment by TheCartpenter** [comment]
Ok, I submitted the change. I removed the array type since the /before event of that method seem to be confronting with the void type from the checkout/success controller since an array of void cannot be done. See if that solved the issue.
