### ISSUE TITLE
Subscription model name was not updated in admin/controller/catalog/product

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#113]
Model name should be updated....also possible need to updated more code

https://github.com/opencart/opencart-3/blob/main/upload/admin/controller/catalog/product.php#L703 as per master branch

https://github.com/opencart/opencart/blob/master/upload/admin/controller/catalog/product.php#L901-L910

**Comment by TheCartpenter** [comment]
I already tagged the subscriptions as being in progress: https://github.com/opencart/opencart-3/issues/82 . I am still working on it. The customer payments (payment methods) also needs to be integrated as to complete the sale/subscription controller, language, and TWIG files in order for store owners to complete their migrations with their subscription plans.
