### ISSUE TITLE
Notice: Undefined property: Proxy::getExtensionsByType

### ISSUE THREAD

**Issue by opencartcomvn** [opencart/opencart-3#118]
index.php?route=checkout/checkout

Notice: Undefined property: Proxy::getExtensionsByType in \system\engine\loader.php on line 243
#########################################
PHP Unknown:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in \system\engine\action.php on line 61
#########################################
Exception: Error: Could not load model catalog/subscription!
admin/index.php?route=catalog/product/edit
admin\controller\catalog\product.php
Line 700
        // Subscription
        $this->load->model('catalog/subscription');

        $data['subscriptions'] = $this->model_catalog_subscriptions->getSubscriptions();
##########################################
 Warning: You do not have permission to modify subscription plans! 
admin\controller\catalog\subscription_plan.php
Line 472
    protected function validateForm() {
        if (!$this->user->hasPermission('modify', 'catalog/subscription')) {
            $this->error['warning'] = $this->language->get('error_permission');
        }

##########################################
Notice: Undefined property: Proxy::addSubscription in
##########################################

**Comment by TheCartpenter** [comment]
Should be fixed now. As for the array|string deprecation message, it's something I might have to look into since it's also on the MB. Please let me know if the other two errors were resolved since the latest patches today.
