### ISSUE TITLE
Catalog JS warnings

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#12]
![catalog_warnings](https://user-images.githubusercontent.com/14251939/169658088-3948db2e-3434-45e1-a19f-437de7fbe988.png)

**Comment by TheCartpenter** [comment]
jQuery version possibly.

**Comment by TheCartpenter** [comment]
What do you see on line 25 of common.js file? Have you also took a look at the network tab?

**Comment by TheCartpenter** [comment]
In addition, if you re-upload the JS package on your store from a previous version including both common.js files. Does the error still show?

**Comment by condor2** [comment]
Line 25: $(document).ready(function () {

No error when you replace before this commit
[Added space on JS functions]

**Comment by TheCartpenter** [comment]
I'll revert the whole JS thing shortly.

**Comment by TheCartpenter** [comment]
Ok, the entire function with spaces have now been reversed.

**Comment by condor2** [comment]
The problem was in catalog... and not admin. Was sufficient to restore only javascript folder

**Comment by TheCartpenter** [comment]
Didn't took any chances. Thank you for the update, however. I'll leave the functions as is on this one.
