### ISSUE TITLE
private array $error = [];

### ISSUE THREAD

**Issue by opencartcomvn** [opencart/opencart-3#126]
Hi
private array $error = [];
syntax error unexpected T_ARRAY unexpected T_FUNCTION or T_CONST
https://www.php.net/manual/en/tokens.php
Older
private $error = array();
So removing the array keyword and just leave it like:
private $error = [];

**Comment by TheCartpenter** [comment]
More information is needed. Which PHP version are you using and which location on the platform did you encountered this error message? Please use the issue template.

**Comment by TheCartpenter** [comment]
According to the PHP error message you are using, you are not using the minimum PHP version of 8.1.
