### ISSUE TITLE
Undefined array key "extension" in

### ISSUE THREAD

**Issue by opencartcomvn** [opencart/opencart-3#131]
Undefined array key "extension" in
catalog/model/checkout/payment_method.php on line 12
catalog/model/checkout/shipping_method.php on line 12

ArgumentCountError:  Too few arguments to function getMethod(),

**Comment by opencartcomvn** [comment]
Also please fix 
system/library/cart/cart.php
Line 236
'date_next'            => $subscription_query->row['date_next'],
date add to cart (1)
date next (2) = (1) + subscription
The idea  automatic sent email invoice or sent email reminder before subscription end
So customer can paid for subscription service

**Comment by TheCartpenter** [comment]
> Undefined array key "extension" in catalog/model/checkout/payment_method.php on line 12 catalog/model/checkout/shipping_method.php on line 12
> 
> ArgumentCountError: Too few arguments to function getMethod(),

Fixed.

**Comment by TheCartpenter** [comment]
> Also please fix system/library/cart/cart.php Line 236 'date_next' => $subscription_query->row['date_next'], date add to cart or date delivery (1) date next (2) = (1) + subscription The idea automatic sent email invoice or sent email reminder before subscription end So customer can paid for subscription service

You'll have to get it approved on the MB first. As for the automation, please see the mail/subscription on both ends in the MB, it's incomplete by design.

**Comment by opencartcomvn** [comment]
Error when add to cart with product has subscription.


```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<b>Warning</b>: Undefined array key "date_next" in <b>/system/library/cart/cart.php</b> on line <b>236
```
