### ISSUE TITLE
Add, Get - Scripts, Styles position Footer

### ISSUE THREAD

**Issue by opencartcomvn** [opencart/opencart-3#139]
Hi,
system/library/document.php
Oder version can add script and style to header and footer from controller
```
$this->document->addScript('catalog/view/javascript/jquery/magnific/jquery.magnific-popup.min.js', 'header');
$this->document->addStyle('catalog/view/javascript/jquery/magnific/magnific-popup.css', 'footer');
```
But not work with this version and MB

`[<b>Warning</b>: Array to string conversion in]`

Please check

**Comment by TheCartpenter** [comment]
Should be fixed, now: https://github.com/opencart/opencart-3/commit/af07bb3c9168ee464ffc94a6ff2fb9d3d1ca3790 .

**Comment by TheCartpenter** [comment]
Send a pull request.
