### ISSUE TITLE
PHP Unknown:  preg_replace()

### ISSUE THREAD

**Issue by opencartcomvn** [opencart/opencart-3#141]
Account link
/index.php?route=account/subscription
The show error
PHP Unknown:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /system/engine/action.php on line 61

**Comment by TheCartpenter** [comment]
I don't see a preg_replace() in the account/subscription controller. Not sure where you pulled that from. Please ensure your tree is synched.

**Comment by opencartcomvn** [comment]
Fresh Installed from latest commit

![Screenshot 2022-11-04 at 00-18-59 Subscriptions](https://user-images.githubusercontent.com/82214791/199790707-964877f0-6b9b-4f4d-9c5a-8276b9372d1c.png)
![Screenshot 2022-11-04 at 00-19-27 Error Log](https://user-images.githubusercontent.com/82214791/199790736-883d300b-46d4-4f83-9fdc-306a3adeffc6.png)

**Comment by TheCartpenter** [comment]
model/checkout is not account/subscription. Re-opening.

**Comment by TheCartpenter** [comment]
Your tree is not synched. It is already changed as an array output: https://github.com/opencart/opencart-3/blob/main/upload/catalog/model/checkout/subscription.php#L23 .

**Comment by TheCartpenter** [comment]
You were reporting for the MB. You posted on the wrong repository. However, I already reported the issue recently: https://github.com/opencart/opencart/pull/11893/commits/73a3ec42806985b1ed516409c9de1b0ea7eedd9a .
