### ISSUE TITLE
Error register with sub product during checkout , error list sub on account

### ISSUE THREAD

**Issue by opencartcomvn** [opencart/opencart-3#145]
<img width="1440" alt="Screen Shot 2022-11-04 at 07 31 52" src="https://user-images.githubusercontent.com/82214791/199860554-51c2613b-e2ce-4560-b9ad-a56544ad5743.png">
<img width="1440" alt="Screen Shot 2022-11-04 at 07 33 19" src="https://user-images.githubusercontent.com/82214791/199860557-47e3e2e5-1a1b-4717-a973-b20f95b3842b.png">
<img width="1440" alt="Screen Shot 2022-11-04 at 07 34 34" src="https://user-images.githubusercontent.com/82214791/199860563-c99c5e0c-1c83-4c3d-9a56-1baf4e3f5c43.png">
<img width="1440" alt="Screen Shot 2022-11-04 at 07 35 19" src="https://user-images.githubusercontent.com/82214791/199860571-d0df62d7-92f2-4fc9-a82a-c279c255087d.png">
<img width="1440" alt="Screen Shot 2022-11-04 at 07 35 59" src="https://user-images.githubusercontent.com/82214791/199860575-a9488799-50a5-4a63-bc71-8e677157ff34.png">

**Comment by opencartcomvn** [comment]
Error: Could not load model marketing/coupon
<img width="1440" alt="Screen Shot 2022-11-04 at 07 59 27" src="https://user-images.githubusercontent.com/82214791/199862721-3184187c-1b19-4929-a3b4-03adcadd9bdf.png">

**Comment by TheCartpenter** [comment]
Screenshot 5, line 4; the line number is missing. I will check for the other errors.

**Comment by TheCartpenter** [comment]
You'll need to post your preg_replace line from the account/subscription controller. It's the 2nd time you're posting this line as you've already been told to post it. Again, I don't see a preg_replace function in that file. As for the other lines, it should be fixed now: https://github.com/opencart/opencart-3/commit/8d4074a7111d0f978a872e8688056b2f751ca2c3 .

**Comment by TheCartpenter** [comment]
Coupon extension model fixed: https://github.com/opencart/opencart-3/commit/e3216d6608e0b783d474126dbe576c1445ec9f31 .
