### ISSUE TITLE
Incomplete code - config_telephone_required

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#156]
Code in setting conteroller

https://github.com/opencart/opencart-3/blob/main/upload/admin/controller/setting/setting.php#L258-L262

Missing from twig
https://github.com/opencart/opencart-3/blob/main/upload/admin/view/template/setting/setting.twig

But is added in customer_form
https://github.com/opencart/opencart-3/blob/main/upload/admin/view/template/customer/customer_form.twig#L101

**Comment by TheCartpenter** [comment]
Yeah, ok. Something doesn't fit right here. I'll take a look at it.

**Comment by TheCartpenter** [comment]
Should be fixed now.

**Comment by condor2** [comment]
Also looks like there are more changes for telephone_required

https://github.com/opencart/opencart/commit/5977f5aa5f694bef0f20952de453bffe5d9c03cb

**Comment by TheCartpenter** [comment]
It is not specifically about the telephone_required field as per your title specifically, but since it is still about the telephone field itself, I'll reopen it.

**Comment by TheCartpenter** [comment]
We can only assume that since you have decided to remove your post that the change you suggested is no longer necessary. Therefore, this commit will now be closed.
