### ISSUE TITLE
Customer approval buttons no twig page load

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#157]
Both functions: aprove and deny doesn't have a page redirect

https://github.com/opencart/opencart-3/blob/main/upload/admin/controller/customer/customer_approval.php#L179

$this->response->setOutput...

**Comment by TheCartpenter** [comment]
Yes, correct. Something is missing here. However, it is not a TWIG file. Since it is a single action that is required per row, whether we need to approve or deny the request, I have another idea for this without the use of a page.

**Comment by TheCartpenter** [comment]
The only problem is the customer_id to be propagated if being done without a TWIG file ... all this for a URL filter that does not respond in the URL bar after the button_filter is hit ...

**Comment by condor2** [comment]
You can make like in oc 4.0.

**Comment by TheCartpenter** [comment]
Won't work with this jQuery version. That's the real issue. In OC 4, the URL do appear on the bar accordingly with the button_filter but previous versions don't (or maybe they used to show a long time ago).

**Comment by condor2** [comment]
Then, maybe like old 2.3.0.2 customer controller?
For approve/deny functions

**Comment by TheCartpenter** [comment]
There's no customer_approval in OC v2.3.0.2 release nor is there a approve/deny ```methods``` as you call them functions.

**Comment by condor2** [comment]
> Then, maybe like old 2.3.0.2 **customer** controller? For approve/deny functions

**Comment by TheCartpenter** [comment]
I know what you're saying. By following that solution, you're still suggesting to separate the ```customer_id``` on a separate page from the URL by adding a new TWIG form page.

**Comment by condor2** [comment]
I sugested like in 2.3.0.2 customer controller.

**customer_approval** controller
**customer_approval_list** twig file

And aprove function to be like


`	public function approve() {
		$this->load->language('customer/customer_approval');

		$this->document->setTitle($this->language->get('heading_title'));

		$this->load->model('customer/customer_approval');

		$customer_approval= array();


			$this->response->redirect($this->url->link('customer/customer_approval', 'user_token=' . $this->session->data['user_token'] . $url, true));
		}

		$this->getList();
	}
`

**Comment by TheCartpenter** [comment]
The controller is not the issue. I will post the changes shortly.

**Comment by TheCartpenter** [comment]
Should be fixed now (at least for this jQuery version): https://github.com/opencart/opencart-3/commit/a6e241a762fa0e2e855c4d43312e566482a5f2fa . For OC 4, it won't be necessary.

**Comment by condor2** [comment]
When you click on button you are log out and the url is 

`customer/customer_approval&amp;user_token=`

**Comment by TheCartpenter** [comment]
> When you click on button you are log out and the url is
> 
> `customer/customer_approval&amp;user_token=`

**Comment by TheCartpenter** [comment]
Updated: https://github.com/opencart/opencart-3/commit/4efcd2cb993f7fd4d7deeeeabee04d0a31e15d1b .

**Comment by condor2** [comment]
Now buttons don't do nothing, just refresh the page

**Comment by TheCartpenter** [comment]
Developers kit.

**Comment by condor2** [comment]
No errors

**Comment by TheCartpenter** [comment]
In the network tab, does it show status 200?

**Comment by condor2** [comment]
Yes

**Comment by TheCartpenter** [comment]
I updated the code.
