### ISSUE TITLE
Bad product delete query

### ISSUE THREAD

**Issue by Griunvaldas** [opencart/opencart-3#160]
https://github.com/opencart/opencart-3/blob/537cc9ade811af3a56cd4d92e4b92399bac8ae94/upload/admin/model/catalog/product.php#L355

Missing ` after table name review

**Comment by TheCartpenter** [comment]
Fixed: https://github.com/opencart/opencart-3/commit/7a17b254784bbb00e94856f892c96d85481d8fca .
