### ISSUE TITLE
Bug in Extension Installer

### ISSUE THREAD

**Issue by Khnaz35** [opencart/opencart-3#161]
Opencart version 3.0.3.9
Default Theme 

**Operating System**
CentOS v7.9.2009

**Server type: MySQL**
Server version: 5.7.41 

**PHP Version ea-php81**

Installing a extension from opencart marketplace "PDF Invoice Pro For Orders" [https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=22647&filter_search=PDF%20Invoice%20Pro%20For%20Orders](url)
Installed the extension via Extension Installer the message was showing successful but Extension/extension> Module doesn't show any extension to installed. 
<img width="309" alt="image" src="https://user-images.githubusercontent.com/43812103/219374122-eee9d453-2fe2-42f9-b8c5-f1eae8944ee1.png">

Same happened with other extension Atome payment.

Only the OCMOD file shows up in modifications. 
<img width="596" alt="image" src="https://user-images.githubusercontent.com/43812103/219374369-931494a4-1abe-4109-ad53-6c0a741d1795.png">

**Comment by TheCartpenter** [comment]
Core extensions are working fine. Since you are addressing 3rd party extensions, please contact each extension developers of those extensions to rectify the issue. Furthermore, PHP version for this branch is meant for 8.2+ .

**Comment by Khnaz35** [comment]
Thanks for reply i did install on 3.0.3.8 and these extensions are working without any issue.
