### ISSUE TITLE
Maintenance mode not working

### ISSUE THREAD

**Issue by neoacevedo** [opencart/opencart-3#165]
I have recently intalled OC 3.0.3.8 via Maintenance branch to work with PHP 8.1.

As I'm starting to setup my store, I put it in maintenance mode the local and online stores but, the maintenance mode page/message isn't working. My store remains with the normal navigation.

Here I setup de maintenance mode:
![imagen](https://user-images.githubusercontent.com/438372/235314543-bdc1ef0c-ffca-4936-88ce-d722dc1cbb45.png)

Here is the online and local store without any message:

![imagen](https://user-images.githubusercontent.com/438372/235314616-dc0b4492-a027-41d7-adf6-aa59ca398164.png)

**Comment by TheCartpenter** [comment]
Joomla is an extension. Contact the extension developer to resolve this issue,

**Comment by neoacevedo** [comment]
@TheCartpenter No, that's a product that I'm currently uploading but I found (I'm still reading the documentation) but if I login in the admin and I go to the frontend, I can see it but if I go to the frontend store in another browser or in a private mode in the browser where I have the admin session opened, I can see the maintenance message. That was made me confuse for a while.

**Comment by TheCartpenter** [comment]
That's definitely a cookie issue. Clear your entire browser's cache and history form. If it's still not working, reset your browser's settings from the internet options (Windows). If using Linux. the cache can even be cleared by command line in your console by Googling it.
