### ISSUE TITLE
Moving storage folder does not work

### ISSUE THREAD

**Issue by MarvinKlein1508** [opencart/opencart-3#168]
After a fresh installation and the first login to admin you'll be promted to move your storage folder.

When clicking on apply, the `config.php` will be changed and an empty folder will be created. However, the files from `system/storage` won't be moved and the shop is broken.

```
Warning: require_once(C:/xampp/storage/vendor/symfony/polyfill-ctype/bootstrap.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\system\vendor.php on line 19

Fatal error: Uncaught Error: Failed opening required 'C:/xampp/storage/vendor/symfony/polyfill-ctype/bootstrap.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\system\vendor.php:19 Stack trace: #0 C:\xampp\htdocs\system\framework.php(5): require_once() #1 C:\xampp\htdocs\system\startup.php(107): require_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\admin\index.php(19): start('admin') #3 {main} thrown in C:\xampp\htdocs\system\vendor.php on line 19
```

**Comment by TheCartpenter** [comment]
Already in the OC forum FAQ: https://forum.opencart.com/viewtopic.php?t=215776#p717782 (first post).

**Comment by MarvinKlein1508** [comment]
@TheCartpenter I cannot find anything related the storage folder at all in this post. Keep in mind that this is not a cache issue since the new folder will be created completely empty. Changing back the config to system/storage works or copy the content of the storage folder manually to the new created folder.

**Comment by MarvinKlein1508** [comment]
To reproduce:
1. Install XAMPP
2. Install latest main branch
3. login to admin
4. hit Move

**Comment by MarvinKlein1508** [comment]
I've just noticed once you click on move there are more folderes created. `storagecache` `storagemodification` and so on. It seems like there is a `/` missing somewhere

**Comment by MarvinKlein1508** [comment]
@TheCartpenter 
Alright. I've tested it now with

- 3.0.3.8
- Opencart Maintenance branch
- And the main branch of this repository

Both opencart 3.0.3.8 and the maintenance branch work just fine. So this might be something related to this branch.

What I've did:

1. Installed Xampp with PHP 8.2
2. Created three subfolders in htdocs (github, release, maintenance)
3. Installed the corresponding Opencart version into the directory
4. Moved to `storage-{directoryname}`

I've ended up with this results:

![grafik](https://github.com/opencart/opencart-3/assets/32510006/b69c04a1-fa11-4ed0-a378-98e71fb02969)


I will take a deeper look into this now. Can you reopen this issue?

**Comment by TheCartpenter** [comment]
In order for this issue to be reopened, the root cause needs to be identified in regard to this branch whereas the issue has not yet been proved nor identified that this branch is, yet, to be the cause.

**Comment by MarvinKlein1508** [comment]
@TheCartpenter the issue is actually caused by the changes within `security.php`

I've compared it with the maintenance branch and there is a key difference.


This is the code from the maintenance branch:
```php
while (count($source) != 0) {
	$next = array_shift($source);

	foreach (glob($next) as $file) {
		// If directory add to path array
		if (is_dir($file)) {
			$source[] = $file . '/*';
		}

		// Add the file to the files to be deleted array
		$files[] = $file;
	}
}
```

In your branch it is:
```php
while (count($source) != 0) {
    $next = array_shift($source);

    if (is_dir($next)) {
        foreach (glob(trim($next, '/') . '/{*,.[!.]*,..?*}', GLOB_BRACE) as $file) {
            // If directory add to path array
            if (is_dir($file)) {
                $source[] = $file . '/*';
            }

            // Add the file to the files to be deleted array
            $files[] = $file;
        }
    }
}
```

Reverting this to the maintenance branches code did fix my issue. Do you remember what you've wanted to achive with this change?

**Comment by MarvinKlein1508** [comment]
The same code has also been applied to the ocmod copy logic. So this is also related to #169

**Comment by TheCartpenter** [comment]
It was taken from OC 4.x releases for updated lookup on the folders. However, OC 4.x users did not seem to report issues in regard to file uploads with their extensions until now. I will revert it.

**Comment by TheCartpenter** [comment]
Fixed: https://github.com/opencart/opencart-3/commit/a19d65523bc1f3183096cb18b06b7ee128559cce .

**Comment by MarvinKlein1508** [comment]
> It was taken from OC 4.x releases for updated lookup on the folders.

I'Ve just checked the file on the Opencart 4 branch. The `*` has been removed from there as well. So I think you've got the code from an early version or you've not seen this one. 

But thanks for the quick fix. Will apply it to our customer soon. I will open new issues when I ran into more issues :)

**Comment by TheCartpenter** [comment]
Yes, indeed. That early code used to be from the maintenance branch which is why I was coding the continuation version of the release. Thanks for addressing those issues. However, while the codes have been reverted, the stars (*) will have to remain since the MB codes for the directory lookups have also been changed compared to the maintenance and, since, the stars (*) have been removed from the MB specifically.
