### ISSUE TITLE
Installation of ocmod doesn't create files

### ISSUE THREAD

**Issue by MarvinKlein1508** [opencart/opencart-3#169]
Installing ocmods doesn't fully work in the main branch.

Content from the `install.xml` will work just fine but all files within the upload directory aren't uploaded to the server. They aren't visible in the database as well.

Take this mod for example
[test.ocmod.zip](https://github.com/opencart/opencart-3/files/11522619/test.ocmod.zip)

I would expect a Module named Test OCMOD but none of these files are actually uploaded to the server. However, the installer says thatz the extension has been installed successfully.

**Comment by MarvinKlein1508** [comment]
I've tracked down the issue to this line.
https://github.com/opencart/opencart-3/blob/5537b4ed1244d59a8dc7b59ee9e2886fcfc9aba1/upload/admin/controller/marketplace/install.php#L116

It seems like it doesn't go through all the sub folders here.

**Comment by MarvinKlein1508** [comment]
You should revert this one as well. Same issue as in `security.php` this one is in `install.php`

**Comment by TheCartpenter** [comment]
Fixed: https://github.com/opencart/opencart-3/commit/efc4bd9e3bb686ec5fe875ee0f07e2386f0913ec .
