### ISSUE TITLE
user/user/getLogins in admin->user management doesn't work

### ISSUE THREAD

**Issue by MarvinKlein1508** [opencart/opencart-3#174]
The user management within the Administration tries to load data from user/user/getLogins, which fails because the variable `{{ user_token }}` is not set within the controller file. It seems like this is some sort of new feature because it is not part of the Opencart 3 Maintenance branch.

The problametic lines are these two:
https://github.com/opencart/opencart-3/blob/f0d125db5b7ed83f0626c04ae58d0cac0acf3de4/upload/admin/view/template/user/user_form.twig#L144

https://github.com/opencart/opencart-3/blob/f0d125db5b7ed83f0626c04ae58d0cac0acf3de4/upload/admin/view/template/user/user_form.twig#L163

![image](https://github.com/opencart/opencart-3/assets/32510006/56cbe7a0-8531-4ee9-87f1-64d910a9f5fc)

Opening the URL manually with a valid user_token returns a blank site with nothing on it.

Is this feature some leftovers from earlier development which can be removed?

**Comment by TheCartpenter** [comment]
Done: https://github.com/opencart/opencart-3/commit/98b2ee604e1a785a69af0b9ff34a18543d4308e4 .
