### ISSUE TITLE
Switching language does not work

### ISSUE THREAD

**Issue by MarvinKlein1508** [opencart/opencart-3#181]
I've installed both English and German in our Store. The frontend shows both languages in the dropdown menu.
![grafik](https://github.com/opencart/opencart-3/assets/32510006/674ec3df-a954-4c83-bb7d-9b3b522ba086)

However selected a language does not switch the language. It seems like you have changed something here to use the GET scheme from Opencart 4. However the form itself sends a POST request. 

Could you please take a look on this?

**Comment by TheCartpenter** [comment]
Please submit a pull request about this issue. I will take a look at it.

**Comment by MarvinKlein1508** [comment]
I'n not familiar with the language system. But it seems like your branch is trying the OC4 approqch. Since the logic is completely different from the Maintenace branch

**Comment by MarvinKlein1508** [comment]
BTW. why did you close this issue when this clearly needs some work?

**Comment by TheCartpenter** [comment]
That is correct, this branch is transitioning with OC4 rather than remaining behind.
