### ISSUE TITLE
Fallback language does not work

### ISSUE THREAD

**Issue by MarvinKlein1508** [opencart/opencart-3#182]
In previous releases of Opencart languages have been using the English language as fallback when it the variable is not beeing defined within the current language. This doesn't seem to be the case anymore. For example take look on Subscriptions:

For example:

![grafik](https://github.com/opencart/opencart-3/assets/32510006/9b016085-4118-45bb-94f4-1215e33fc755)

**Comment by TheCartpenter** [comment]
As mentioned before, subscription codes aren't completed yet.

**Comment by MarvinKlein1508** [comment]
@TheCartpenter this isn't just for subscriptions. I've used them as an example because they don't have a German translation. Old version of Opencart would display English then instead of nothing

**Comment by TheCartpenter** [comment]
The old OC version contained the deprecated recurring fields and values whereas the recent OC versions no longer uses them.
