### ISSUE TITLE
Event's result is empty scalar but not NULL

### ISSUE THREAD

**Issue by jigius** [opencart/opencart-3#189]
I have encountered a problem. The problem lies in the value returned from a specific event in one of the models. In the case where the result is an empty array, such a value is discarded in `loader.php`. 
https://github.com/opencart/opencart-3/blob/91fe45dd2f9db34401f24fa5eb01a82701fb2ee0/upload/system/engine/loader.php#L224
I believe that when handling events, their results should be checked for `NULL` in the `callback()` and `view()` methods of the `loader.php` file.

**Comment by TheCartpenter** [comment]
Neither repositories have this integration with ```null```. This code is improvised as you haven't posted your server specs by using the template.  Please post both versions with and without the use of ```$result``` or address the topic URL where you see this solution does actually solves the issue.
