### ISSUE TITLE
seo_url::rewite() may returns an incorrect URL

### ISSUE THREAD

**Issue by jigius** [opencart/opencart-3#191]
In a time when there is no defined seo-keyword for a category param in a link - seo_url::rewite() may returns an incorrect URL.

#### Example:

`product_id=123` has `seo_keyword=parrot`
`category_id=78` has no seo_keyword

rewite's input is:
`http://example.com/index.php?route=product/product&path=78&product_id=123`

output awaiting:
`http://example.com/parrot?path=78`

but result is:
`http://example.com/parrot`

---
I've wrote 10 tests to show the issue: 
[https://github.com/jigius/opencart-3/tree/issue-seo-params](https://github.com/jigius/opencart-3/tree/issue-seo-params)

Run `php upload/issues/seo-path/test.php`

**Comment by TheCartpenter** [comment]
I don't see either repositories that have this code. It's been addressed so many times before. It's an issue with your ```.htaccess```. You should need to configure it properly.

**Comment by jigius** [comment]
The test shows the issue on the repository without deploying its on a http-server.

**Comment by TheCartpenter** [comment]
The only test it shows is the result that is based on your ```.htaccess``` file. Neither branch contains this solution. You just need to tweak the file a bit.

**Comment by jigius** [comment]
i'm puzzled about the mention of the .htaccess file :( I do not undestand how .htaccess influence to a result which  has being gotten from the test cli-script if .htaccess is just a part of the apache http-server/mod_rewrite?
