### ISSUE TITLE
Cookie notification bar need to be changed

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#196]

**Comment by TheCartpenter** [comment]
To what? Any PRS?

**Comment by condor2** [comment]
I made once or 2 PR.......then you have changed back.....

v4 cookie bar
![oc4_cookie_bar](https://github.com/opencart/opencart-3/assets/14251939/1b792b04-e0f6-4db5-a280-367f74360faa)

vs

v32_cookie_bar
![oc32_cookie_bar](https://github.com/opencart/opencart-3/assets/14251939/80bbfdd8-6b68-4b56-a63e-4d99c5ad47af)

**Comment by TheCartpenter** [comment]
> I made once or 2 PR.......then you have changed back.....
> 
> v4 cookie bar ![oc4_cookie_bar](https://user-images.githubusercontent.com/14251939/278864829-1b792b04-e0f6-4db5-a280-367f74360faa.jpg)
> 
> vs
> 
> v32_cookie_bar ![oc32_cookie_bar](https://user-images.githubusercontent.com/14251939/278864847-80bbfdd8-6b68-4b56-a63e-4d99c5ad47af.jpg)

The CSS class name you pointed doesn't exist in the ```stylesheet.css``` file. That's why. Please ensure the class names are relevant and existent unless creating a new CSS class name along with your PRs.

**Comment by condor2** [comment]
What CSS class name? Is just a title know wich images is from v4 and v32....

**Comment by TheCartpenter** [comment]
The text footer is already merged: https://github.com/opencart/opencart-3/pull/158
