### ISSUE TITLE
GDPR form design need to be changed

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#197]
Old
![old_gdpr](https://github.com/opencart/opencart-3/assets/14251939/1d1acf55-d16a-4e45-a938-ddceacb781e3)

New
![new_gdpr](https://github.com/opencart/opencart-3/assets/14251939/4152f35d-d5cc-4d86-b1b6-83543ab87cea)

**Comment by TheCartpenter** [comment]
Yeah, GDPR is already on my TODO-list. I'll leave this commit opened, for now.

**Comment by condor2** [comment]
Also GDPR url is not showing in the footer when is enabled...

Add GDPR by Default in Layout section

**Comment by TheCartpenter** [comment]
Ok, will look into that.

**Comment by TheCartpenter** [comment]
> Also GDPR url is not showing in the footer when is enabled...
> 
> Add GDPR by Default in Layout section

The text footer is already merged: https://github.com/opencart/opencart-3/pull/158

**Comment by condor2** [comment]
For GDPR design, copy from here and make some changes if are needed

https://github.com/condor2/Opencart_30xx/blob/master/upload/catalog/view/theme/default/template/information/gdpr.twig

**Comment by TheCartpenter** [comment]
> For GDPR design, copy from here and make some changes if are needed
> 
> https://github.com/condor2/Opencart_30xx/blob/master/upload/catalog/view/theme/default/template/information/gdpr.twig

Create a PR about it. That's how we'll speed things up.

**Comment by TheCartpenter** [comment]
```form-check``` class is only for PayPal. Not used for OC v3.x releases with cheboxes. Your class name declarations in that file are not the right ones.

**Comment by TheCartpenter** [comment]
Updated: https://github.com/opencart/opencart-3/commit/79201bddad966d64ebacbabbe23e402ac53b6989
