### ISSUE TITLE
Still a few unresolved ecb issues

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart-3#206]
I think you have to replace all calls to

`$this->model_setting_extension->getInstalled('currency');
`
with

`$this->model_setting_extension->getExtensionsByType('currency');`

Also, the admin/language/en-gb/setting/setting.php has some missing entries:

```
$_['entry_currency_engine']          = 'Currency Rate Engine';
....
$_['help_currency_auto']             = 'Set your store to automatically update currencies daily. It requires a chosen Currency Rate Engine.';

```

And in the **System > Localisation > Currencies** it comes up with the wrong info message:

**This extension requires the EUR currency.**

Only when you try to refresh the currencies should it check for existence of the EUR when the ECV is the chosen currency engine.

Nothing major, not hard to fix it all.

**Comment by TheCartpenter** [comment]
It was never about how hard people thinks it is, it is rather how quick the issue can be reported to fix it.

**Comment by mhcwebdesign** [comment]
Just added another pull request https://github.com/opencart/opencart-3/pull/207 with some final bugfixes. I grabbed them from the 3.0.x.x, and they should also work for this opencart-3 repository. Tested it all for opencart-3 to be sure.
