### ISSUE TITLE
Bootstrap 3.4.1 and sanitize: false,

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#210]
If I will do a pull request with Bootstrap 3.4.1, to work popover function is needed to add

`sanitize: false,`

is ok for you?

**Comment by TheCartpenter** [comment]
I was about to post for this to @danielkerr since he's the one who accepted your PR. Better, yet, to confirm before integrating this. So far, with the new jQuery version, does this also fix the File Manager issue that was previously reported on the 3.0.x.x repository?

**Comment by condor2** [comment]
On 3.0.x.x is same
https://github.com/opencart/opencart/commit/25ff238f6ccac5633423de5922b152b4c480d9ee

**Comment by TheCartpenter** [comment]
Yes, I know. Which is why I am asking, without integrating the ```sanitize: false``` right now, does it affect the File Manager from the admin since jQuery has been updated?

**Comment by TheCartpenter** [comment]
Ok. Create a PR for it and we'll see to it for a merge.

**Comment by TheCartpenter** [comment]
Since .popover work without ```sanitize: false``` then we may not need to use ```sanitize: false``` since we haven't, yet, upgraded to Bootstrap 3.4.1 .

**Comment by TheCartpenter** [comment]
@condor2: Now that jQuery has been upgraded, to answer your initial question with Bootstrap v3.4.1, you can also give it a try for a PR.

**Comment by TheCartpenter** [comment]
I also noticed the catalog-end side still uses the old jQuery version. It might need to be upgraded as well.

**Comment by TheCartpenter** [comment]
It has been merged, now: https://github.com/opencart/opencart-3/pull/211
