### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#22]
Fatal error: Uncaught TypeError:

Argument 1 passed to Session\File::__construct() must be an instance of Session\Registry, instance of Registry given, called in system\library\session.php on line 29 and defined in system\library\session\file.php:4

Stack trace: 

0 system\library\session.php(29): Session\File->__construct(Object(Registry))
1 system\framework.php(88): Session->__construct('file', Object(Registry))
2 system\startup.php(104): require_once('...')
3 install\index.php(37): start('install')
4 {main} thrown in system\library\session\file.php on line 4

**Comment by TheCartpenter** [comment]
Done: https://github.com/opencart/opencart-3/commit/c505043dfe7a2636ff4f83d6876349359d4cb09c .
