### ISSUE TITLE
Missing address_format_id column from oc_country table

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#23]
In the table is `address_format` text NOT NULL,  (oc_country)

**Comment by TheCartpenter** [comment]
Please submit pull requests about them. It could be merged if the case since those addressed issues are about specific codes or database fields.

**Comment by TheCartpenter** [comment]
Done with address_format: https://github.com/opencart/opencart-3/commit/709a8df9bf19a7ba1ae5e8efc943d3ca61101f8b . From now on, please, about codes or database fields, create a pull request.
