### ISSUE TITLE
Access to an undefined property ControllerExtensionPaymentSquareup::$squareup

### ISSUE THREAD

**Issue by AJenbo** [opencart/opencart-3#239]
I don't see where the squareup is loaded, @TheCartpenter if you can find the place where that happens then I can help with how to define it in a way that is detectable.

**Comment by TheCartpenter** [comment]
Sure, here's the entire list about Squareup:

- admin/controller/extension/payment/squareup.php
- admin/language/en-gb/extension/payment/squareup.php
- admin/model/extension/payment/squareup.php
- admin/view/template/extension/payment/squareup_recurring_buttons.twig
- admin/view/template/extension/payment/squareup_order.twig
- admin/view/template/extension/payment/squareup_transaction_info.twig
- admin/view/template/extension/payment/squareup.twig
- catalog/controller/extension/credit_card/squareup.php
- catalog/controller/extension/payment/squareup.php
- catalog/controller/extension/subscription/squareup.php
- catalog/language/en-gb/extension/payment/squareup.php
- catalog/model/extension/credit_card/squareup.php
- catalog/model/extension/payment/squareup.php
- catalog/view/theme/default/template/extension/payment/squareup.twig
- install/opencart.sql
- system/library/squareup/cron.php
- system/library/squareup/cron_functions.php
- system/library/squareup.php
- system/library/squareup/exception.php

**Comment by TheCartpenter** [comment]
system/library/squareup/cron.php file launches the cron_functions.php file to initialize the extension.

As for the ```Squareup::``` instances to use that library, followed are all the files:

- admin/controller/extension/payment/squareup.php
- catalog/controller/extension/payment/squareup.php
- catalog/controller/extension/subscription/squareup.php
- catalog/model/extension/payment/squareup.php

**Comment by AJenbo** [comment]
Please show me where it gets loaded, it will probably look like this (this is where the user property is loaded):
https://github.com/opencart/opencart-3/blob/9083551301fd63316d7da31bff51ddf1dd810ad8/upload/admin/controller/startup/login.php#L22

**Comment by TheCartpenter** [comment]
It's not loaded part of the ```$registry``` object. This one's an exception. It has been integrated backwards a long time ago from the library with a vendor in order to be launched from the ```cron_functions.php``` file. Then, to use the object as: ```Squareup::``` in the platform. It is not a regulated integration as if we'd normally pass the ```$registry->set``` with the engine.

**Comment by TheCartpenter** [comment]
Their vendors package can be found on Github: https://www.github.com/sqaure/square-php-squareup-sdk/blob/master

**Comment by AJenbo** [comment]
It's here it looks like:

https://github.com/opencart/opencart-3/blob/ec2a7614d1035b8177ff9cc35c8c2cfccda6e20d/upload/catalog/controller/extension/credit_card/squareup.php#L99

**Comment by TheCartpenter** [comment]
It also has to be on the admin-end since the object is still being used from the controller but no library attached to those calls.

**Comment by AJenbo** [comment]
OC is not structured well enough to be able to determine that beforehand.

**Comment by TheCartpenter** [comment]
I believe it's the only core extension that works like this. The other ones are using the vendors with their own models in the extension folders. I don't know why Squareup should be any different which is also one of the reason I integrated the ```vendor.php``` with ```$autoloader``` to avoid that kind of issue happening in the future hopefully.
