### ISSUE TITLE
Warning: Undefined property: Loader::$model_setting_setting system\library\googleshopping\traits\storeloader.php on line 10

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#248]

**Comment by TheCartpenter** [comment]
Also worked on these codes and posted on my last update.

**Comment by condor2** [comment]
This warning is using latest branch

**Comment by TheCartpenter** [comment]
Should be fixed now: https://github.com/opencart/opencart-3/commit/0774a992abedb0b88cac383991c00dc3393af5fa .
