### ISSUE TITLE
TypeError: Cannot assign null to property Router::$error of type object in system\engine\router.php on line 72 - GDPR

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#253]
Go to GDPR
![gdpr](https://github.com/opencart/opencart-3/assets/14251939/28eddfa2-84c7-4489-9fdb-7363935f6fce)

**Comment by TheCartpenter** [comment]
Should be fixed now: https://github.com/opencart/opencart-3/commit/28209bc39d48a07dcead9b8c418055389da83285 . I'll take a look for the ```%s days```.

**Comment by TheCartpenter** [comment]
Should work now.
