### ISSUE TITLE
Cannot assign Action to property Router::$error of type ?string in system\engine\router.php:43

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#255]
When you try to install

Stack trace:

#0 system\framework.php(195): Router->dispatch()
#1 system\startup.php(107): require_once('...')
#2 install\index.php(40): start() 
#3 {main} thrown in system\engine\router.php on line 43

**Comment by TheCartpenter** [comment]
Removed: https://github.com/opencart/opencart-3/commit/d1c7e41d74f9533c8cf662605b2e537cc7d4eb83 .
