### ISSUE TITLE
Install error when use backslash and enum

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#256]
With these changes in database you can't install opencart.

`enum(\'day\',\'week\',\'semi_month\',\'month\',\'year\') NOT NULL, `

**Comment by TheCartpenter** [comment]
Reversed: https://github.com/opencart/opencart-3/commit/33528ed05a6eb6a6be5e29f095ca7a1508d9cfc0 .

**Comment by condor2** [comment]
@TheCartpenter controllers should be reversed also.
