### ISSUE TITLE
Not working anymore on PHP 8.0/8.1

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#26]

**Comment by TheCartpenter** [comment]
The part I am noticing where codes have been added before I was assigned is under admin/controller/startup/startup.php and catalog/controller/startup/startup.php (__isset method) files. There were also a few strings added into the models that I didn't do as also where you could take a look.

**Comment by TheCartpenter** [comment]
Also, check your developers kit and your server error logs.

**Comment by condor2** [comment]
Maintenance branch worked just fine

https://github.com/opencart/opencart/commit/2b2b7581f9af1ea7ec10f75c2d35277095c5c774

**Comment by condor2** [comment]
Catalog side

Unknown: mysqli::real_escape_string(): Passing null to parameter #1 ($string) of type string is deprecated in system\library\db\mysqli.php on line 53Warning: Undefined array key "api_id" in system\library\cart\cart.php on line 36
Fatal error: Uncaught Exception: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0' at line 1<br/>Error No: 1064<br/>0 in system\library\db\mysqli.php:48 Stack trace: #0 system\library\db.php(45): DB\MySQLi->query(0) #1 system\library\cart\cart.php(36): DB->query(0) #2 system\library\cart\cart.php(331): Cart\Cart->getProducts() #3 catalog\controller\common\cart.php(10): Cart\Cart->getTaxes() #4 system\engine\action.php(78): ControllerCommonCart->index(Array) #5 system\engine\loader.php(48): Action->execute(Object(Registry), Array) #6 catalog\controller\common\header.php(77): Loader->controller('common/cart') #7 system\engine\action.php(78): ControllerCommonHeader->index(Array) #8 system\engine\loader.php(48): Action->execute(Object(Registry), Array) #9 catalog\controller\common\home.php(17): Loader->controller('common/header') #10 system\engine\action.php(78): ControllerCommonHome->index() #11 catalog\controller\startup\router.php(25): Action->execute(Object(Registry)) #12 system\engine\action.php(78): ControllerStartupRouter->index() #13 system\engine\router.php(66): Action->execute(Object(Registry)) #14 system\engine\router.php(55): Router->execute(Object(Action)) #15 system\framework.php(169): Router->dispatch(Object(Action), Object(Action)) #16 system\startup.php(104): require_once('C:\\xampp\\htdocs...') #17 index.php(19): start('catalog') #18 {main} thrown in system\library\db\mysqli.php on line 48

**Comment by TheCartpenter** [comment]
And to think that the escape() method was referred from the master branch for a null look up. I presume things may not work as well on that side. Very well, I'll restore the original escape() method on all DB libraries. As for the api_id, I haven't worked on that one in system/library/cart/cart.php file. Must probably be a leftover bug in there.

**Comment by TheCartpenter** [comment]
In system/library/cart/cart.php file, if you replace back:

```$cart_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "cart` WHERE `api_id` = '" . (isset($this->session->data['api_id']) ? (int)$this->session->data['api_id'] : 0) . "' AND `customer_id` = '" . (int)$this->customer->getId() . "' AND `session_id` = '" . $this->db->escape($this->session->getId()) . "'");```

Does it now work?

**Comment by condor2** [comment]
> Does it now work?

Yes

**Comment by TheCartpenter** [comment]
Well received; here's all the bug-fixes for this issue: https://github.com/opencart/opencart-3/commit/35ad135b98a1d7c2699937b5f4e8f028d4bdda0d .

**Comment by condor2** [comment]
Admin side (PHP 7.4)

Fatal error: Uncaught Error: Class 'Googleshopping' not found in system\library\googleshopping\traits\libraryloader.php:8

**Comment by TheCartpenter** [comment]
That means that PHP 8 may not like when removing parentheses on isset from the models. Got it.

**Comment by TheCartpenter** [comment]
> Admin side (PHP 7.4)
> 
> Fatal error: Uncaught Error: Class 'Googleshopping' not found in system\library\googleshopping\traits\libraryloader.php:8

Which route in the admin?

**Comment by condor2** [comment]
When try to login

**Comment by TheCartpenter** [comment]
In admin/controller/extension/advertise/google.php file,

in the __construct() method, replace:

```$this->store_id = isset($this->request->get['store_id']) ? (int)$this->request->get['store_id'] : 0;``

with:

```$this->store_id = (isset($this->request->get['store_id']) ? (int)$this->request->get['store_id'] : 0);```

does it work now?

**Comment by TheCartpenter** [comment]
Rest of the bug-fixes for this issue: https://github.com/opencart/opencart-3/commit/8b4c821c77eb43c204e3dfaaf27dff73a9f7e698 . Will have to look for more in the core.

**Comment by TheCartpenter** [comment]
Added as extra ones in case: https://github.com/opencart/opencart-3/commit/da6617526f1d7cb9a23d1bb4db14bdeddd73b831 .

**Comment by condor2** [comment]
Catalog side, PHP 8.1

Unknown: mysqli::real_escape_string(): Passing null to parameter #1 ($string) of type string is deprecated in system\library\db\mysqli.php on line 53

**Comment by condor2** [comment]
After I bypassed google module another error

Notice: Undefined property: Proxy::editValueByCode in system\engine\loader.php on line 248

**Comment by TheCartpenter** [comment]
Please open a new incident request. This Google extension might be something that wasn't expected in the past. I'll take a look at it.
