### ISSUE TITLE
Order form not loaded

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#264]
Is something wrong in first group of javascript code.

Also there is a typo
https://github.com/opencart/opencart-3/blob/main/upload/admin/view/template/sale/order_form.twig#L2299-L2300

**Comment by TheCartpenter** [comment]
Fixed: https://github.com/opencart/opencart-3/commit/b246e08149bb9496d54251bb1f4249365d5509e7 .

**Comment by condor2** [comment]
Not fixed

Error: Could not load template sale/order_form!

**Comment by TheCartpenter** [comment]
More info is needed here. How do you obtain that error? By doing what?

**Comment by condor2** [comment]
Sales->Orders, click on Add new.

**Comment by TheCartpenter** [comment]
The method and order_info.twig file does exist in the directory. Are you sure the file does exist on your end?

**Comment by condor2** [comment]
Fixed
https://github.com/opencart/opencart-3/pull/269

**Comment by TheCartpenter** [comment]
Merged: https://github.com/opencart/opencart-3/pull/269
