### ISSUE TITLE
GDPR is not loaded from admin menu

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#265]
Also, there is no pagination in controller.

**Comment by TheCartpenter** [comment]
Fixed: https://github.com/opencart/opencart-3/commit/29a389be6811a7ea5220a0396e2c9183d325d4bb .

**Comment by TheCartpenter** [comment]
For the admin menu, it also checks for permissions. Make sure the permissions are checked from the user/user_permission route.
