### ISSUE TITLE
Analytics warning after is installed

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#273]
<b>Warning</b>: Array to string conversion in <b>system\storage\cache\template\de\de5e4fb7f5ba0df83e13c4adcc27ec96.php</b> on line <b>121</b>Array

`        echo ($context["analytics_google_code"] ?? null);`

**Comment by TheCartpenter** [comment]
Fixed: https://github.com/opencart/opencart-3/commit/8aeaf04a99091ca476e94a051a9caa6292a96410 .
