### ISSUE TITLE
Customer account subscription URL not loaded with "int start"

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#279]
With this modification in subscription model, subscription page/url not working from customer account

`public function getSubscriptions(int $start = 0, int $limit = 20): array {`

warning displayed

TypeError: ModelAccountSubscription::getSubscriptions(): Argument #1 ($start) must be of type int, array given, called in system\storage\modification\system\engine\loader.php on line 265 in catalog\model\account\subscription.php on line 63

work with
`public function getSubscriptions($start = 0, int $limit = 20): array {`

**Comment by TheCartpenter** [comment]
Fixed: https://github.com/opencart/opencart-3/commit/7ec0f4d5f3baecb6270f2f91c47de304bbd95584 .
