### ISSUE TITLE
Typed property Action::$route must not be accessed before initialization

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#280]
Load the store and replace in the url with this

`/index.php?route=test/test`

You will get the warning

Error: Typed property Action::$route must not be accessed before initialization in system\storage\modification\system\engine\action.php on line 60

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart-3/commit/766697021903d1e558dc7c1d2af5e2fc6da06b0e .
