### ISSUE TITLE
Uncaught TypeError: Loader::callback()

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#282]
Admin and catalog not loaded anymore

Fatal error: Uncaught TypeError: Loader::callback(): Return value must be of type array, Closure returned in system\engine\loader.php:291

Stack trace:
0 system\engine\loader.php(100): Loader->callback()
1 catalog\controller\event\translation.php(18): Loader->model()
2 system\engine\action.php(93): ControllerEventTranslation->index()
3 system\engine\event.php(58): Action->execute()
4 system\engine\loader.php(231): Event->trigger()
5 system\framework.php(166): Loader->language()
6 system\startup.php(107): require_once('...')
7 index.php(22): start()
8 {main} thrown in system\engine\loader.php on line 291

**Comment by TheCartpenter** [comment]
Ok, will leave it as a mixed type since it seem to be based on the route location expecting various outputs.

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart-3/commit/c03237f9e4de8bb6ce12b2f9ff785be2371c6801
