### ISSUE TITLE
Deprecated: Required parameter $fcm_id follows optional parameter $cart_id in /home/afrauae/storage/modification/catalog/model/checkout/order.php on line 58

### ISSUE THREAD

**Issue by Technicalbiluji** [opencart/opencart-3#285]
If you want to request an explanation from the OpenCart team regarding the deprecated parameter order issue, you can do so by reaching out to them through their official channels. This could include their support forums, GitHub repository (if the project is open-source), or their official website's contact page.

When reaching out, it's helpful to provide context about the specific error message you're encountering, including the file and line number where it occurs, just like you did here. This allows their team to understand the issue more quickly and provide you with a relevant explanation or solution.

Here's a template you might use for your inquiry:

---
Dear OpenCart Team,

I hope this message finds you well. I'm currently working with OpenCartVersion 3.0.3.8, and while troubleshooting an issue, I encountered the following error message:

```
Deprecated: Required parameter $fcm_id follows optional parameter $cart_id in /home/afrauae/storage/modification/catalog/model/checkout/order.php on line 58
```

After reviewing the code, I believe this issue might be related to the order of parameters in a function call within the `order.php` file. However, I'd appreciate further clarification from your team regarding the cause of this deprecation warning and any recommended actions to resolve it properly.

Could you kindly provide an explanation for this deprecated parameter order issue and any guidance on how to address it effectively?

Thank you for your assistance.

Sincerely,
Bilal Khan.

---

**Comment by TheCartpenter** [comment]
$fcm_id originates from an extension of yours.
