### ISSUE TITLE
do you have plan to upgrade jquery and bootstrap to the latest version?

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart-3#293]
do you have plan to upgrade jquery and bootstrap to the latest version?

**Comment by TheCartpenter** [comment]
The TWIG files still uses the old bootstrap classes as OC 4x releases already has one of the most upgraded jQuery version even though, even there, bootstrap is not upgraded to the latest version.

**Comment by chongshengdz** [comment]
this version has lots of errors need to be fixed.

**Comment by TheCartpenter** [comment]
Create new pull requests if you believe there are lots of errors, I will take a look at them.
