### ISSUE TITLE
jQuery errors after admin login

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#30]
![jquery_error](https://user-images.githubusercontent.com/14251939/173198698-5e2c1854-186c-4144-8a5c-74dacfb14683.png)

**Comment by condor2** [comment]
Same on catalog side

**Comment by TheCartpenter** [comment]
Not quite sure on this one. I'll re-upload both javascript folders to see if that solves.

**Comment by condor2** [comment]
Same issue

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart-3/commit/dbec26f9687bd56c08b2f2a0a5d6b4126a6e6c7c . We can see some differences in the files. If it would entirely be the same issue, then the differences wouldn't be shown ...

Have you replaced both javascript folders from the maintenance branch already?

**Comment by condor2** [comment]
only in admin, and same issue

**Comment by TheCartpenter** [comment]
Check your developers kit from, both, console and network tabs. Also your server error logs regarding controller issues.

**Comment by condor2** [comment]
Also there is an issue with the session.
I need to change admin password every time when I am logut

**Comment by TheCartpenter** [comment]
With a customer's account, are you able to login without getting kicked out?

**Comment by TheCartpenter** [comment]
If not, I'll restore both customer and user libraries.

**Comment by condor2** [comment]
> With a customer's account, are you able to login without getting kicked out?

After log out I can't login anymore

**Comment by TheCartpenter** [comment]
I've reverted, both, customer and user library files. Clear your browsing history. See if it works.
