### ISSUE TITLE
Admin custom_fields bug when a Customer is edited

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#37]
If a customer has 2 custom_fields: one is for Account (named **custom_field_account**) second is for Affiliate (named **custom_field_affiliate**)
When customer is edited and both custom_fields are filled in with values, these values are inserted together in database in both tables.

customer table
customer_affiliate table
When custom_field_account value should be inserted only in customer table and custom_field_affiliate value should be inserted only in customer_affiliate table.

Or I think is much better to change admin affiliate structure like in 4.0 Marketing->Affiliate

**Comment by TheCartpenter** [comment]
Yes, that reflection did crossed my mind yesterday. I'll take a look at the admin marketing.

**Comment by condor2** [comment]
With old Admin structure custom fields are inserted like this
![oc_customer](https://user-images.githubusercontent.com/14251939/173316465-7b279566-6f33-4318-9bc8-99370f65752f.png)

**Comment by condor2** [comment]
On Master branch there is no issue because Affiliate code was  moved from Customer to Marketing

**Comment by TheCartpenter** [comment]
Since a pull request has now been created on your behalf, this commit will now be closed.
