### ISSUE TITLE
Google Shopping error admin load

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#40]
admin load if you change this line 

$this->registry->set('googleshopping', new \Googleshopping($this->registry, $store_id));

to

$this->registry->set('googleshopping', new Googleshopping($this->registry, $store_id));

from 
https://github.com/opencart/opencart-3/blob/main/upload/system/library/googleshopping/traits/libraryloader.php#L8

**Comment by TheCartpenter** [comment]
Please create a pull request. The issues tab is about design issues, not about lines of codes.

**Comment by condor2** [comment]
I thought you'd check why it doesn't work with new \Googleshopping ....

**Comment by TheCartpenter** [comment]
By posting the error messages, along with your pull requests, codes can be merged a lot faster once they make sense. ;)
