### ISSUE TITLE
Affiliate is not added in database

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#48]
When you register directly from affiliate/register in database is added only as Customer.

**Comment by TheCartpenter** [comment]
Pull request, please. It's a subject we're already dealing with over there.

**Comment by TheCartpenter** [comment]
Found the reason. I'll fix it.

**Comment by TheCartpenter** [comment]
Done: https://github.com/opencart/opencart-3/commit/21e6d7205dd119534c8ed55283792cbe46dd62c1 .

**Comment by condor2** [comment]
Is not about custom_fields...

Is about addAffiliate function

https://github.com/opencart/opencart-3/blob/main/upload/catalog/model/account/customer.php#L129

**Comment by TheCartpenter** [comment]
After
