### ISSUE TITLE
[Bug] Cart is empty

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#51]
Possible session bug
https://github.com/opencart/opencart-3/blob/main/upload/catalog/controller/startup/session.php#L29

Work if you change that line to 'expires'  => 0,  ,but I don't know if is a good solution

**Comment by TheCartpenter** [comment]
Are you using file or db for the cache? Also, please post your developers kit's results as well as your server error logs. I did tested the add-to-cart function and, since the vouchers commit fix, I was able to successfully add products to the cart.

**Comment by TheCartpenter** [comment]
It's not a good solution for 0. Did you also configured your admin > systems > settings > edit settings page for the config_session_expire option?

**Comment by TheCartpenter** [comment]
Furthermore, use a print_r on your $option array and see what the 'expires' key outputs from its value.

**Comment by condor2** [comment]
Array ( [expires] => 1655290793 [path] => /oc3/ [secure] => [httponly] => [SameSite] => Strict )

**Comment by TheCartpenter** [comment]
If you modify the config_session_expire from database, does the 'expires' key value from the array changes as well?

**Comment by condor2** [comment]
Expires key change every time I hit refresh

 [expires] => 1655291643
[expires] => 1655291653

**Comment by condor2** [comment]
After changed in database to 6800000000

it show
 [expires] => 1655291881

**Comment by TheCartpenter** [comment]
Echo your $this->config->get('config_session_expire') on your browser and see what it outputs. Also, did you merged the changes since its integration?

**Comment by condor2** [comment]
Can you give a hint?
I am not a guru in debugging =)))))

**Comment by TheCartpenter** [comment]
Has this commit solved the issue since? https://github.com/opencart/opencart-3/pull/52

**Comment by condor2** [comment]
It show 6800000000 as it in database

**Comment by TheCartpenter** [comment]
On OC4, are you able to add products to the cart with the 'expires'  key?

**Comment by condor2** [comment]
Success: You have added Iphone to your shopping cart.
But when you click on shopping cart is empty

**Comment by condor2** [comment]
If you leave only

'expires'  => (int)$this->config->get('config_session_expire'),

cart show the products.

**Comment by TheCartpenter** [comment]
GDPR has a maximum extent of 1 year with these cookies by law so this needs to be followed carefully.

**Comment by condor2** [comment]
yes, but is weird why don't work with the time...

**Comment by TheCartpenter** [comment]
Do you notice the same behavior on the master branch?

**Comment by condor2** [comment]
Not understand why expires values are not the same...
Is like + doesn't work...

4.0
Array ( [expires] => 8455297801 [path] => /oc40/ [secure] => [httponly] => [SameSite] => Strict )

3.0
Array ( [expires] => 1655297804 [path] => /oc3/ [secure] => [httponly] => [SameSite] => Strict )

both oc same session expire in database

**Comment by condor2** [comment]
Added 

time() + 6800000000 and it show like in 4.0.

I think config_session_expire can't be read.

**Comment by TheCartpenter** [comment]
In system/config/catalog.php file, if you move startup/session after startup/startup, is the $this->config->get now working with the 'expires' ?

**Comment by TheCartpenter** [comment]
I think I found the problem. In the master branch, the setting/setting was created and put first into the catalog.php array. By not doing that, the $this->config->get will never be loaded. Added that to the list.

**Comment by condor2** [comment]
With session second store crash

Notice: Indirect modification of overloaded property ControllerStartupStartup::$session has no effect in catalog\controller\startup\startup.php on line 114

**Comment by TheCartpenter** [comment]
Yes, it's probably the default.php file that needs to be properly ordered when loading the tasks. I'll look into it.

**Comment by TheCartpenter** [comment]
Working on it now.

**Comment by TheCartpenter** [comment]
Testing completed on the catalog end-side.

- Restructured loading on startup files as per master branch with the exception of languages and SEOs
- Tested currency exchange dropdown: Works
- Tested Add-to-Cart with sessions: Works (catalog/controller/startup/session.php file was the issue)
- Added $option in all startup files that required it: Works.

**Comment by TheCartpenter** [comment]
Going to work on the admin-end.

**Comment by condor2** [comment]
Enjoy :) 
![IMG_20220615_194844](https://user-images.githubusercontent.com/14251939/173883046-e9564bd1-88d6-46ff-996e-c1605eabbc59.jpg)

**Comment by TheCartpenter** [comment]
Task completed for the admin startup files. Samesite should now be working on both ends whenever, either, a customer or a user logs into their accounts. This commit will now be closed.
