### ISSUE TITLE
ArgumentCountError: Too few arguments to function

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#58]
With SMTP enabled

ArgumentCountError: Too few arguments to function Mail\Smtp::__construct(), 0 passed in system\library\mail.php on line 35 and exactly 1 expected in system\library\mail\smtp.php on line 20

**Comment by TheCartpenter** [comment]
See if this solution rectifies the issue: https://github.com/opencart/opencart-3/commit/1dbf3595d8ea12426e0ba07e24b7d41114144ea2 . If not, see on OC v4 if the same issue occurs with mail and SMTP.
