### ISSUE TITLE
Restore javascript from installer

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#59]
A bunch of javascript error and you can't upgrade

**Comment by condor2** [comment]
![java_install](https://user-images.githubusercontent.com/14251939/174042674-926caeed-69b1-4d9e-8e0c-7edccdbe6197.png)

**Comment by TheCartpenter** [comment]
Older JS libraries can't even handle best practices with spaced parentheses on functions even in TWIG files. :(

Very well, I'll restore them and see if that can solve. At least, would be a good reason to upgrade this thing so that it can handle recent JS libraries from JS developers that may require the use of space like the master branch. Otherwise, we'll still be stuck later on until OC4 ...

**Comment by TheCartpenter** [comment]
Done: https://github.com/opencart/opencart-3/commit/b9d32d4e74aab45e52fc9c7c7c2a1c297eac5609 .

**Comment by condor2** [comment]
> Older JS libraries can't even handle best practices with spaced parentheses on functions even in TWIG files. :(

If you don't like jquery 3.6.0 :))

**Comment by TheCartpenter** [comment]
Yeah, something that's probably going to be considered to handle future JS packages. Is it working again since the trimmed functions?

**Comment by condor2** [comment]
Yes, with 3.6.0 work just fine

**Comment by TheCartpenter** [comment]
Then, this is becoming a normal priority. Could you create a pull request again for this integration - only branches about JS, 'nothing else' - on this one? We're not putting ```sanitize false```, however, you'll have to find another way to fit this in.

**Comment by TheCartpenter** [comment]
Will JS 3.6.0 handle the current bootstrap.min library as well? If not, OC v4 already has an updated bootstrap version with updated TWIG files.

**Comment by TheCartpenter** [comment]
According to this commit post: https://github.com/twbs/bootstrap/issues/30644#issuecomment-817120080 , at least, Bootstrap 3.4.1 would need to be used. Currently, the Bootstrap version is: 3.3.5; still too low which means that Bootstrap would also need to be upgraded.

**Comment by TheCartpenter** [comment]
Since the primary subject of this commit has been resolved, it will now be closed.
