### ISSUE TITLE
Undefined variable $config in install\model\upgrade\1009.php on line 140

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#61]
line 140 is this

$config_captcha_page = json_decode((array)$config->get('config_captcha_page'), true);

**Comment by TheCartpenter** [comment]
Done: https://github.com/opencart/opencart-3/commit/b17cad796a5bf1f08a623b8f0533f5ffee465a68 . Not much choice to move the $config object outside of the affiliate in this case. Also removed the true case from the admin setting model with json_encode. This was a bug.
