### ISSUE TITLE
how to combine duplicate custom_field name with value opencart version 3038?

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart-3#65]
how to combine duplicate custom_field name with value opencart version 3038?
admin=>order info=>Account Custom Fields
before combination:
Account Custom Fields
color yellow
color green
color red
image 3ba9557e23ecb68b0152683e2623dd72907bdfff
image MPX2102AP.jpg
size big
size small
after combination, the chart will show like:
Account Custom Fields
color: yellow,green,red
image: 3ba9557e23ecb68b0152683e2623dd72907bdfff, MPX2102AP.jpg
size: big, small
how to do it?
![combine](https://user-images.githubusercontent.com/30888843/174646270-c8448b1b-c008-4755-99a9-248284ad110b.jpg)

**Comment by chongshengdz** [comment]
below is the original code:
					if ($custom_field['type'] == 'checkbox' && is_array($order_info['custom_field'][$custom_field['custom_field_id']])) {
						foreach ($order_info['custom_field'][$custom_field['custom_field_id']] as $custom_field_value_id) {
							$custom_field_value_info = $this->model_customer_custom_field->getCustomFieldValue($custom_field_value_id);

							if ($custom_field_value_info) {
								$data['account_custom_fields'][] = array(
									'name'  => $custom_field['name'],
									'value' => $custom_field_value_info['name']
								);
							}
						}
					}

**Comment by TheCartpenter** [comment]
Please see this post in order to test in your admin > customers > custom field's list page: https://forum.opencart.com/viewtopic.php?f=202&t=228850&p=844988#p844988 before heading to the orders.

**Comment by chongshengdz** [comment]
> Please see this post in order to test in your admin > customers > custom field's list page: https://forum.opencart.com/viewtopic.php?f=202&t=228850&p=844988#p844988 before heading to the orders.

not working, I just need to combine the duplicate custom names with values if there are more than one custom names.

**Comment by chongshengdz** [comment]
I just need to combine the duplicate custom names with values if there are more than one custom names.
this means: only one custom name allowed with different values if there are more than one custom values.

**Comment by chongshengdz** [comment]
please see the attached photo:
before combination:
![combine](https://user-images.githubusercontent.com/30888843/174721447-60dc2551-b3dd-4dc9-b3cf-4f72e995efaa.jpg)
after combination:
![after-combination](https://user-images.githubusercontent.com/30888843/174721463-55c419ac-ed06-4db1-81e8-d316c20978cb.jpg)
the modification should be as the after-combination.
