### ISSUE TITLE
Typo's Setting.twig

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#69]
What is this?

https://github.com/opencart/opencart-3/blob/main/upload/admin/view/template/setting/setting.twig#L829

**Comment by TheCartpenter** [comment]
Ok, will look on this one.

**Comment by TheCartpenter** [comment]
Done: https://github.com/opencart/opencart-3/commit/68eb1ee5846d7a3fb8d7ac860dcc6df490db9f1b .
