### ISSUE TITLE
Cookie buttons class

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#79]
Why you have reverted class for cookie buttons?
![cookie_buttons](https://user-images.githubusercontent.com/14251939/176990135-a9bebfc3-7c9d-48e5-88fb-a864d6571000.png)

More nice this way...
![cookie_buttons_ok](https://user-images.githubusercontent.com/14251939/176990185-f1b2b6e9-68cd-4024-8241-e8982d279bae.png)

**Comment by TheCartpenter** [comment]
Will restore it.

**Comment by TheCartpenter** [comment]
Done.

**Comment by condor2** [comment]
btn-block doesn't exist in bootstrap 3
