### ISSUE TITLE
Wrong linking to account/affiliate

### ISSUE THREAD

**Issue by MarvinKlein1508** [opencart/opencart-3#92]
In both the footer and the account panel the links go to account/affiliate. However this controller has no index function which results in an issue in routing:

TypeError: Cannot assign null to property Router::$error of type object in /home/webpages/lima-city/marvinkleinmusic/opencart/system/engine/router.php on line 75

For example:
https://opencart.marvinkleinmusic.de/index.php?route=account/affiliate&customer_token=ZYtncbCKYLgQZ82k5c4zi75Qor

In the account panel it should either redirect to account/affiliate/add or account/affiliate/edit

In the footer it should link to affliate/login 

Otherwise nobody can signup for the affiliate program.

**Comment by TheCartpenter** [comment]
Pull request, please.
