### ISSUE TITLE
PHP 8.1 errors

### ISSUE THREAD

**Issue by haxcop** [opencart/opencart-3#93]
HI. 
upgrading a current staging installation from 3.0.3.6 to 3.0.3.8 I found the following errors
Steps to reproduce:
Navigated to the folder installation. 

1. Run `composer update`
2. <store.local>/install 
3. Finish installation (many errors encounter with the current opencart.sql ) I had to adjust this manually (push request on the way)
4. Navigate to the store and /admin area
5. Errors: 
6. `PHP Unknown:  preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in /home/user/storage/vendor/scssphp/scssphp/src/Parser.php on line 1151`
7. ` PHP Unknown:  preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in/home/user/storage/vendor/scssphp/scssphp/src/Parser.php on line 1232`
8. `Automatic conversion of false to array is deprecated in /home/user/storage/modification/catalog/controller/startup/startup.php on line 115`
9. `PHP Unknown:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/user/storage/modification/catalog/controller/startup/seo_url.php on line 60`
10. `PHP Unknown:  Return type of Twig\Markup::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/user/storage/vendor/twig/twig/src/Markup.php on line 35`
11. `PHP Unknown:  Return type of Twig\Markup::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/user/storage/vendor/twig/twig/src/Markup.php on line 40`

**Comment by TheCartpenter** [comment]
You are posting in the OC v3.1.1.0 repository. The catalog/controller/startup/startup.php file, line 115 for instance, does not exist. Therefore, please either post on the OC forum or on the maintenance branch in regards to the OC v3.0.3.8 release.

**Comment by TheCartpenter** [comment]
As far as the opencart.sql file, you mentioned to have fixed many issues but none of them were reported based on what you claimed was broken.

**Comment by haxcop** [comment]
Hey Thanks for the clarification in regards of the repros, I was confused as this error also was reported on the branch you mentioned but Daniel closed the bug and ask you guys to open the same here. 
In regards of the opencart.sql
i just added logics to the date / datetime formats and changed MyISAM to InnoDB including an update on the charset and collations 
I will do the pull request in a few minutes, feel free to review and merge it if is feasible, for me it its and works.
Thanks again
