### ISSUE TITLE
admin: edit order -> if select from combobox lost data for last step

### ISSUE THREAD

**Issue by SoftwareMagicIT** [opencart/opencart-3#99]
When update order address, if use combobox for select order I have this. Checked on 2 differents installations of Opencart 3.0.3.8 See attachments
![address change](https://user-images.githubusercontent.com/16600519/193003538-7d4e9f39-04ea-4b00-95d1-011d46bb1934.png)
![error](https://user-images.githubusercontent.com/16600519/193003571-c1c24b08-b61e-4a51-a4d3-f185f080aeb1.png)

**Comment by TheCartpenter** [comment]
Please post your server access logs and developers kit screenshots (console and network tab) during the error message.

**Comment by SoftwareMagicIT** [comment]
2022-09-29 15:05:36 - PHP Notice:  Undefined index: total in /home/vl658nd6/public_html/admin/model/customer/customer.php on line 450

I see session data empty after combo selection

**Comment by TheCartpenter** [comment]
Extension. Look at the file and line.
